### ISSUE TITLE
Synchronize between two machines

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_Map-Drive-Inator#11]
Hi @EdoFro 

I just made a new test to verify that everything works because I use the synchronization of some maps via Nextcloud between my personal machine (linux) and my pro machine (windows). I believe that a number of Freeplane users are in this situation. 

While my settings are set to relative links ( `../` ), MapDriveInator does not recognize the "basefolder" path when switched to Windows. 

![image](https://user-images.githubusercontent.com/29939805/213670085-8118aee5-2c9d-4f2e-b96a-2362d6c9b07d.png)

Is it supposed to work with this usage ?

**Comment by EdoFro** [comment]
did it work with the previous MDI scripts?

**Comment by bepolymathe** [comment]
I'm not sure I've ever tried 🤔

**Comment by bepolymathe** [comment]
It worked independently on windows and linux but I had not tried until now to synchronize the same card.... which would be very convenient!

**Comment by EdoFro** [comment]
Can you see if the baseFolderNode really has a relative link?

when looking at its link. example:

Absolute:
![image](https://user-images.githubusercontent.com/35700575/213698272-d019073d-538b-4e4d-8fe9-4b5750d89891.png)

Relative:
![image](https://user-images.githubusercontent.com/35700575/213698704-35207070-c105-43da-b2c3-845dd63371f1.png)

**Comment by bepolymathe** [comment]
Yes it’s a relative format

![image](https://user-images.githubusercontent.com/29939805/213699354-e7ce94e0-7e5e-4ed0-8274-7d0be23082c4.png)

**Comment by bepolymathe** [comment]
Oh wait... 
I realize that my synchronize folder must be in the root of the file system under linux and in the "Documents" folder under windows...

**Comment by EdoFro** [comment]
ok. I´m looking at it.

**Comment by EdoFro** [comment]
ok. I know now how to solve this, but it will requier more effort and tima. At the end MDI wil be capable of handling relative links.

But this will require lots of intervention and testing.

I think I will do it, but this solution won't be able in the short term.

**Comment by bepolymathe** [comment]
Okay, no problem waiting. I am available to do the necessary tests...

**Comment by EdoFro** [comment]
here is the solution I currently use:

I add a node with links to the different paths depending the computer I'm using and execute a script that changes all the links.

When I change to other computer or get back to the first one, I execute the script again.

It works.

![image](https://user-images.githubusercontent.com/35700575/213723705-52a1335d-b69d-48a8-91dc-1a853855f342.png)


#### instructions:
1. add the node "possible paths" as child of the baseFolderNode
    - it has to have the locked style
2. add as child of that node the different locations of the base folder
    - dragndrop the folder every time you go to a computer where its path is different
    - this way you will add all necesary alternatives
3. execute the script in node "Check in v6"

Here is an example map with the script:
[prueba.zip](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/files/10467109/prueba.zip)

**Comment by EdoFro** [comment]
solved #23
