### ISSUE TITLE
Allow nodes to have links

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_Map-Drive-Inator#15]
Hi @EdoFro 

I noticed a behavior that I find a bit annoying but I don't know if a simple workaround exists... If I integrate in my folder tree a node that contains a link to another node (not a visual link but link with ID), it is systematically detected as a broken link ("missing" style) at the time of MDI sync. 🤔

**Comment by EdoFro** [comment]
Ok. I could replicate the issue. I'm going to work on it.

**Comment by bepolymathe** [comment]
It is strange. Since the update to version 0.0.6 I can't create folders anymore 🤔

**Comment by bepolymathe** [comment]
@EdoFro 

Apparently the latest version 0.0.6 is a problem. All my existing folders are recognized as new. Creating a new folder works but on the next sync it displays a broken link. Deleting the whole thing and re-importing everything does not change the problem. Do you have the same problem?

**Comment by EdoFro** [comment]
@bepolymathe 

1. can you please try with a new mindmap. applying the styles and applying MDI?

2. can you please share the mindmap you are having problems with?
   - or just export a dummy node as new map using the commad "Move branch to new map" and share that map with me.
   - this way I can see all the styles and style conditional rules you have and make some test on my own.

**Comment by bepolymathe** [comment]
Hi, 

Some illustrations in video

[Capture vidéo du 2023-02-01 14-41-17.webm](https://user-images.githubusercontent.com/29939805/216059986-f998fd0f-c388-4088-ab13-0d2656242753.webm)

And test file 

[Test MDI.zip](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/files/10557605/Test.MDI.zip)

**Comment by bepolymathe** [comment]
And branch export as map. I will remove these files once you get them back. 

[Nuage.zip](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/files/10557696/Nuage.zip)

**Comment by EdoFro** [comment]
> And branch export as map. I will remove these files once you get them back.
> 
> [Nuage.zip](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/files/10557696/Nuage.zip)

ok delete them

**Comment by bepolymathe** [comment]
> can you share the first lines of your Log.0 file:

Yep. 

```
STDOUT: févr. 01, 2023 2:38:12 PM org.freeplane.core.util.LogUtils info
INFOS: freeplane_version = 1.11.1 alpha; freeplane_xml_version = freeplane 1.11.1
git revision = 1faf137430f04c361298b512da3d910b92669f9c Dimitry Polivaev 2023-01-20T20:14:17Z
java_version = 17.0.5; os_name = Linux; os_version = 6.1.7-200.fc37.x86_64
STDOUT: Framework launched
STDOUT: févr. 01, 2023 2:38:14 PM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: févr. 01, 2023 2:38:14 PM org.freeplane.core.util.LogUtils info
INFOS: extending script's classpath by [/home/bepolymathe/.config/freeplane/1.11.x/compiledscripts, /home/bepolymathe/.config/freeplane/1.11.x/addons/bookmarks/lib/bookmarks.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/markdownHelper/lib/MarkdownHelper.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/markdownHelper/lib/jsoup-1.10.2.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/markdownHelper/lib/markedj-1.0.16.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/mapSavingOptions/lib/MapSavingOptions.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/jumper/lib/jumper.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/menuOMatic/lib/Menu-o-Matic.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/freeplane-zotero/lib/freeplane-zotero.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/mapDriveInator/lib/MapDriveInator.jar, /home/bepolymathe/.config/freeplane/1.11.x/lib]
```

**Comment by EdoFro** [comment]
can you send me one of the same maps, but the version before the error?

**Comment by bepolymathe** [comment]
Yes. A version of yesterday before the new MDI version installation. 

[Journal de bord.zip](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/files/10557847/Journal.de.bord.zip)

**Comment by EdoFro** [comment]
I updated [ v.0.0.6](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/releases/tag/v0.0.6). please try it and tell me

**Comment by bepolymathe** [comment]
It looks like it's working again. Thanks a lot !!!
