### ISSUE TITLE
how to exactly use this?

### ISSUE THREAD

**Issue by grotesque** [EdoFro/Freeplane_Map-Drive-Inator#27]

**Comment by EdoFro** [comment]
I have had no time to update the documentation. I'm prioritizing that the add-on works properly and then I will release a new documentation.

**Comment by EdoFro** [comment]
Hi,
I will update the README file of the project in the near future (hopefully this week).

My idea is to create a "quick starting guide" and I will write it as simple and short as possible. I want to post every change directly to Github, so you can see how it goes. 

I hope to have your feedback so I can make a better documentation.

I will post here every time I update the file, so you get a message and are informed about it.

bye,

edo

**Comment by Vadeinspace** [comment]
Absolutely, thanks for replying and for sharing your work.

**Comment by EdoFro** [comment]
I added a little quick starting guide: #39 
BR
edo
