### ISSUE TITLE
How to find the node with a problem

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_Map-Drive-Inator#35]
Hi Edo, 

I have this message that mention "mapPosition" problem...

![image](https://user-images.githubusercontent.com/29939805/221691888-4cb8ffe3-1837-4d53-b5c8-fd478adcb930.png)

How can i search for this node.

**Comment by EdoFro** [comment]
this is not a problem. It says that you have two (or more) clones that have links to a file. For one of them its position in the map doesn't match its position in the drive (link path), but it has a clone where its link matches its map position.

--> there is no problem. ("They were OK") 

in other words:
When using clones: if one clone is ok, then everything is ok!

So, if you move a clone to another folderNode, but the original stays in its folder then MDI doesn't move the file in the drive.

I don't know if I can explain it better.

BR

edo

**Comment by bepolymathe** [comment]
Yes, thank you, it's clear and that's what I understood. Just, once moved I can't find a way to identify which node with clone has a broken link.

**Comment by EdoFro** [comment]
no clone has a broken link. They have the same link, but only one of them is correctly placed in the Map (path in Map = link)

**Comment by bepolymathe** [comment]
Yes, sorry, I misspoke. I just wanted to find this node but I had trouble identifying it. But I found it now. Thanks for your answers to my silly questions ;-)

**Comment by EdoFro** [comment]
No problem. I'm working on a new version and I'm adding more (and clearer) log information, so the user can see in the Freplane's log which files were moved in the drive, which couldn't get moved, the id of their nodes, etc.
This way you, as user, will have a way to identify those cases.

**Comment by bepolymathe** [comment]
Great ! Thank you.
