### ISSUE TITLE
The new version does not import styles

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_Map-Drive-Inator#8]
Hi @EdoFro 

Thanks a lot to you for making the effort to turn MapDriveInator into an addon. 

I just tried the 0.0.4 version on my linux machine (freeplane 1.11.1). It seems that the styles needed to make the addon work are not imported during the installation and I have the following error message. 

![image](https://user-images.githubusercontent.com/29939805/213134439-5ee659de-73e3-48b4-b2cf-6ab0bcd47d99.png)

Maybe it would be possible to add the possibility to add them like you did for the MarkdownHelper addon with the "Import MDH styles" command?

**Comment by EdoFro** [comment]
[v0.0.5](https://github.com/EdoFro/Freeplane_Map-Drive-Inator/discussions/10)

please test it and close this issue if it's ok

**Comment by bepolymathe** [comment]
Hi @EdoFro 

I confirm it works like a charm ! Thanks a lot. It change my life ;-)
